# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('fundtype', models.IntegerField(null=True)),
                ('parentfund', models.CharField(max_length=100)),
                ('childfund', models.CharField(max_length=100)),
                ('dateinception', models.DateField(null=True)),
                ('datedue', models.DateField(null=True)),
                ('channel', models.CharField(max_length=100)),
                ('custodian', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('share', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('nvmultipleier', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('nvplus', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('manager', models.CharField(max_length=100)),
                ('team', models.IntegerField(null=True)),
                ('priority', models.IntegerField(null=True)),
                ('sortindex', models.IntegerField(null=True)),
                ('splitratio', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('splitratio_pr', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('splitration_temp', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('bounusthisyear', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('accountid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dealprice', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
