# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='bounusthisyear',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='childfund',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='custodian',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='datedue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='dateinception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fundid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fundtype',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='nvmultipleier',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='nvplus',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='parentfund',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='producttype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='sortindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='splitratio',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='splitratio_pr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='splitration_temp',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='accountid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='dealprice',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
