# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20171129_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
